express-post-json - Susana Gutierrez
Susana-Gutierrez/m2-0921-code-solutions pull request #30
Opened 2021-11-17 06:35 UTC by Susana-Gutierrez

https://user-images.githubusercontent.com/82625148/142147166-bc1d1674-c175-41f2-ab70-8a88d04a7153.mp4

2021-11-18 17:41 UTC, TimelikeClosure requested changes

2021-11-18 17:41 UTC, TimelikeClosure commented on express-post-json/index.js
> +});
`grades` should contain every grade (like in `express-get-json`), not just one.

2021-11-19 04:17 UTC, Susana-Gutierrez commented
https://user-images.githubusercontent.com/82625148/142564072-75c6559f-7260-4c58-9a30-33929ad02847.mp4

2021-11-19 04:21 UTC, TimelikeClosure approved these changes

2021-11-19 04:22 UTC, merged